### ISSUE TITLE
Header Menu Issue

### ISSUE THREAD

**Issue by towel1017** [GSM-Web-Technology/Jub-Jub-Client#132]
1. 일반 유저 로그인 시 텍스트가 회원가입에서 로그아웃으로 렌더링 되지 않는 오류
![image](https://user-images.githubusercontent.com/48384442/110295905-0460b200-8035-11eb-8603-b8b215044560.png)

2. 로그아웃 후 "/" 라우터로 이동하면서 로그인, 회원가입 버튼의 위치가 서로 바뀌는 오류
![image](https://user-images.githubusercontent.com/48384442/110296146-50abf200-8035-11eb-8854-9c80e31c1e4f.png)

-> Header 컴포넌트의 styled-component가 admin일 시와 아닐 때의 float 속성이 다름, 렌더링 후 고쳐지지 않았음. (token과 연관 가능성 O)

**Comment by sunwoo0706** [comment]
2번 이슈는 css float의 문제인듯합니다.
